name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: RELEASE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Version
        run: |
            export BUILD_VERSION=$(jq -r '.version' package.json)
            echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            lens-extension-menu-${{ env.BUILD_VERSION }}*.tgz

